### PR TITLE
support 1.18.2

### LINKED ISSUE #15: 1.18.2 Update

### PR DESCRIPTION
**Pull request by superloach**
Swapped `DynamicRegistryManager.Impl` for the new `DynamicRegistryManager.ImmutableImpl`, since the previous `Impl` was an immutable one, and it built successfully. Haven't tested too extensively, but it does work!

Should close #15.

### CODE REVIEW

**Comment by juster-0** [comment]
Have you tried to play with it? I can open minecraft with this build, but the game crashes every time when I try to open any world.
```
Minecraft: 1.18.2
MultiMC: 0.6.15-3244
Fabric API: 0.48.0+1.18.2
Mod Menu: 3.1.0
Fabric Loader: 0.13.3
```

**Comment by superloach** [comment]
Do you have crash logs? I didn't actually test too much 😅

**Comment by juster-0** [comment]
Yep. Can you check?
[Crash Log](https://gist.github.com/juster-0/7b29e0a2e898bbcb9f90453267a753c8)

**Comment by superloach** [comment]
Looks like there's a type mismatch on the PlayerManager.LOGGER field, they switched from log4j to sfl4j in 1.18.2. I'll see if I can fix this later when I get home.

**Comment by juster-0** [comment]
I've found [fork](https://github.com/KosmX/Custom-LAN) with working 1.18.2 version, I've not tested fully, but `Open to LAN` and `/op` `/deop` commands and changing port work, so I think we can just open pull request from the fork.

**Comment by superloach** [comment]
Yeah, that fork looks good. I'll close this PR, @DimiDimit will you check out that fork and merge if you find it acceptable?

**Pull request closed without merging**
